# Generated by Django 5.0.7 on 2024-08-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите товар', max_length=100, verbose_name='Товар')),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание товара')),
                ('date_created', models.DateField(help_text='Введите дату добавления', verbose_name='Дата добавления')),
                ('category', models.CharField(choices=[('Процессоры', 'Процессоры'), ('Материнские платы', 'Материнские платы'), ('Видеокарты', 'Видеокарты'), ('Оперативная память', 'Оперативная память'), ('SSD-диски', 'SSD-диски'), ('HDD-диски', 'HDD-диски'), ('Блоки питания>', 'Блоки питания')], max_length=50, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену товара', max_digits=10, verbose_name='Цена товара')),
                ('photo', models.ImageField(blank=True, help_text='Введите фото', null=True, upload_to='images', verbose_name='Фото товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
